apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bbq-api-31
  name: bbq-api-31
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bbq-api-31
  strategy: {}
  template:
    metadata:
      labels:
        app: bbq-api-31
    spec:
      containers:
      - image: massimocrippa/bbq-api
        name: bbq-api-31
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bbq-api-31
  labels:
    app: bbq-api-31
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 80
  selector:
    app: bbq-api-31
  type: LoadBalancer